import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import MainApp from "./components/main";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <MainApp />
          {children}
          <footer>
            Icons by{" "}
            <a target="_blank" href="https://icons8.com" className="underline">
              Icons8
            </a>
          </footer>
        </Providers>
      </body>
    </html>
  );
}
